spring:
  application:
    name: YJ-HelloWorld-Zookeeper
  cloud:
    zookeeper:
      discovery:
        enable: true
loggin:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

rmi:
  service:
    name: HelloRmi
    port: 9999
    host: 127.0.0.1



